<?php
/*
 * Set specific configuration variables here
 */
return [
        'routes' => true,
        'four_square_client_id'         =>  'G10AJFRMN14ZWOSAHBCZ3JUU1K23SBT2PZMFLBF4XWFP23XS',
        'four_square_client_secret'     =>  'VCKE5DW5FQLSVZW3YJ3VWSY5GAQPNJVDWKVRTXSTT2MNBKXN',
        'four_square_end_point'         =>  'https://api.foursquare.com/v2/venues/search?',
        'modules'                       =>  [
                     "google"       =>          '713',
                     "yahoo"        =>          '462',
                     "facebook"     =>          '559',
                     "bing"     =>          '483',
                     "yelp"     =>          '439',
                     "mapquest"     =>          '420',
                     "superpages"       =>          '433',
                     "citysearch"       =>          '402',
                     "foursquare"       =>          '440',
                     "insiderpages"     =>          '662',
                     "merchantcircle"       =>          '398',
                     "publicreputation"     =>          '767',
                     "elocal"       =>          '551',
                     "ezlocal"      =>          '733',
                     "localdatabase"        =>          '761',
                     "showmelocal"      =>          '469',
                     "topix"        =>          '434',
                     "citysquares"      =>          '524',
                     "localpages"       =>          '516',
                     "yellowmoxie"      =>          '505',
                     "tupalo"       =>          '502',
                     "navmii"       =>          '532',
                     "whereto"      =>          '523',
                     "uscity"       =>          '543',
                     "eightcoupons"     =>          '547',
                     "n49dotca"     =>          '595',
                     "yasabe"       =>          '562',
                     "getfave"          =>              '392',
                     "golocal247"           =>              '563',
                     "pointcom"         =>              '578',
                     "ablocal"          =>              '579',
                     "opendi"           =>              '580',
                     "findlocal"            =>              '583',
                     "cylex"            =>              '638',
                     "iglobal"          =>              '645',
                     "ibegin"           =>              '644',
                     "yalwa"            =>              '690',
                     "brownbook"            =>              '692',
                     "aroundme"         =>              '716',
                     "kudzu"            =>              '732',
                     "findopen"         =>              '768',

        ]
];